/** Common job titles for autocomplete — expandable or replaceable with an external API. */
export const JOB_TITLES: readonly string[] = [
  "Software Engineer",
  "Senior Software Engineer",
  "Staff Software Engineer",
  "Principal Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Mobile Developer",
  "iOS Developer",
  "Android Developer",
  "DevOps Engineer",
  "Site Reliability Engineer",
  "Cloud Engineer",
  "Data Engineer",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI Engineer",
  "Product Manager",
  "Senior Product Manager",
  "Product Owner",
  "Technical Product Manager",
  "Program Manager",
  "Project Manager",
  "Engineering Manager",
  "Director of Engineering",
  "VP of Engineering",
  "Chief Technology Officer",
  "UX Designer",
  "UI Designer",
  "Product Designer",
  "Graphic Designer",
  "Marketing Manager",
  "Digital Marketing Manager",
  "Growth Marketing Manager",
  "Content Marketing Manager",
  "SEO Specialist",
  "Social Media Manager",
  "Sales Representative",
  "Account Executive",
  "Business Development Representative",
  "Sales Manager",
  "Customer Success Manager",
  "Account Manager",
  "Financial Analyst",
  "Investment Analyst",
  "Accountant",
  "Controller",
  "Human Resources Manager",
  "Recruiter",
  "Talent Acquisition Specialist",
  "Operations Manager",
  "Business Analyst",
  "Management Consultant",
  "Strategy Consultant",
  "Legal Counsel",
  "Paralegal",
  "Registered Nurse",
  "Physician",
  "Physical Therapist",
  "Pharmacist",
  "Teacher",
  "Professor",
  "Instructional Designer",
  "Research Scientist",
  "Laboratory Technician",
  "Mechanical Engineer",
  "Electrical Engineer",
  "Civil Engineer",
  "Chemical Engineer",
  "Manufacturing Engineer",
  "Quality Assurance Engineer",
  "Test Engineer",
  "Security Engineer",
  "Cybersecurity Analyst",
  "Network Engineer",
  "Systems Administrator",
  "Database Administrator",
  "Solutions Architect",
  "Enterprise Architect",
  "Scrum Master",
  "Agile Coach",
  "Technical Writer",
  "Copywriter",
  "Editor",
  "Journalist",
  "Video Producer",
  "Photographer",
  "Executive Assistant",
  "Office Manager",
  "Administrative Assistant",
  "Supply Chain Manager",
  "Logistics Coordinator",
  "Warehouse Manager",
  "Retail Store Manager",
  "Chef",
  "Restaurant Manager",
  "Real Estate Agent",
  "Property Manager",
  "Architect",
  "Interior Designer",
  "Construction Manager",
  "Electrician",
  "Plumber",
  "Founder",
  "Co-Founder",
  "CEO",
  "COO",
  "CFO",
  "CMO",
  "CPO",
  "Head of Product",
  "Head of Growth",
  "Head of Design",
  "Head of Sales",
  "Head of Marketing",
  "VP of Product",
  "VP of Sales",
  "VP of Marketing",
  "Intern",
  "Associate",
  "Analyst",
  "Specialist",
  "Coordinator",
  "Director",
  "Vice President",
];

export function searchJobTitles(query: string, limit = 8): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];

  const scored: { title: string; score: number }[] = [];

  for (const title of JOB_TITLES) {
    const lower = title.toLowerCase();
    if (!lower.includes(q)) continue;

    let score = 0;
    if (lower.startsWith(q)) score += 10;
    if (lower === q) score += 20;
    const wordStart = lower.split(/\s+/).some((w) => w.startsWith(q));
    if (wordStart) score += 5;
    score -= lower.length * 0.01;

    scored.push({ title, score });
  }

  return scored
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((s) => s.title);
}
